version: "2"

services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
      dev_network:
        ipv4_address: 172.28.1.2

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    ports:
      - "80:80"
    volumes_from:
      - app
    working_dir: /var/www
    networks:
      dev_network:
        ipv4_address: 172.28.1.1

  redis:
    image: redis:latest
    networks:
      dev_network:
        ipv4_address: 172.28.1.3

  beanstalkd:
    build:
      context: ./
      dockerfile: beanstalkd.dockerfile
    ports:
      - "11300:11300"
    networks:
      dev_network:
        ipv4_address: 172.28.1.4

  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sweedy
      POSTGRES_USER: sweedy
      POSTGRES_PASSWORD: secret
    networks:
      dev_network:
        ipv4_address: 172.28.1.5

networks:
  dev_network:
    ipam:
      config:
      - subnet: 172.28.0.0/16
